apiVersion: v2
publisher: Mikhail Arkhipov
name: rtool
version: 0.0.26
type: VS Code extension
displayName: rtool
title: rtool
description: >-
  R Tools (IntelliSense, signature help, tooltips and more).
icon: /v3/images/ms-python-python-icon.png
category: Programming Languages
repository: 'https://github.com/MikhailArkhipov/vscode-r'
firstPublicationDate: '2021-08-21'
latestUpdateDate: '2017-03-23'
spec:
  extensions:
     - 'https://raw.githubusercontent.com/nupurnegi/jupyter_plugin/main/Mikhail-Arkhipov.r-0.0.26.vsix'
