apiVersion: v2
publisher: ms-toolsai
name: jupyter
version: latest
type: VS Code extension
displayName: Jupyter
title: Jupyter
description: >-
  Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit
  tests, snippets, and more.
icon: /v3/images/ms-python-python-icon.png
category: Programming Languages
repository: 'https://github.com/Microsoft/vscode-python'
firstPublicationDate: '2020-07-16'
latestUpdateDate: '2021-04-29'
spec:
  extensions:
    - 'https://raw.githubusercontent.com/nupurnegi/jupyter_plugin/main/newExtensions/ms-toolsai.jupyter-2022.3.1000632050.vsix'
    - 'https://raw.githubusercontent.com/nupurnegi/jupyter_plugin/main/newExtensions/ms-toolsai.jupyter-renderers-1.0.6.vsix'
    - 'https://raw.githubusercontent.com/nupurnegi/jupyter_plugin/main/newExtensions/ms-toolsai.jupyter-keymap-1.0.0.vsix'
    - 'https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix'
