apiVersion: v2
publisher: ms-python
name: python
version: latest
type: VS Code extension
displayName: Python
title: Python
description: >-
  Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit
  tests, snippets, and more.
icon: /v3/images/ms-python-python-icon.png
category: Programming Languages
repository: 'https://github.com/Microsoft/vscode-python'
firstPublicationDate: '2020-07-16'
latestUpdateDate: '2021-04-29'
spec:
  extensions:
    - 'https://github.com/microsoft/vscode-python/releases/download/2020.2.62710/ms-python-release.vsix'
    - 'https://raw.githubusercontent.com/nupurnegi/jupyterserver/main/jupyterserver-0.0.1.vsix'

    
